version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: cafe-web
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - /var/tmp
      - sockets:/app/tmp/sockets
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    environment:
      RAILS_ENV: production
      # これがないとwebpackがcompileされないので注意
      RAILS_SERVE_STATIC_FILES: 1
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    networks:
      - cafe-production
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
      #socketファイルの共有
    volumes:
      - sockets:/app/tmp/sockets
      - public-data:/app/public
      - tmp-data:/app/tmp
    depends_on:
      - web
    networks:
      - cafe-production

networks:
  cafe-production:

volumes:
  sockets:
  public-data:
  tmp-data:
  log-data:



