version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rails-cafe
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - tmp-data:/app/tmp
      - sockets:/app/tmp/sockets
      - public-data:/app/public
    environment:
      RAILS_ENV: development
      # RAILS_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - db
      - chrome
    tty: true
    stdin_open: true
    networks:
      - cafe

  db:
    image: postgres:9.6.2-alpine
    container_name: db-cafe
    environment:
      POSTGRES_PASSWORD: 12345678
      TZ: "Asia/Tokyo"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    networks:
      - cafe

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_LISTEN_PORT: 80
    ports:
    - 8080:80
    depends_on:
      - db
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"
    networks:
      - cafe

  chrome:
    # 本番用
    # image: selenium/standalone-chrome:latest
    # デバッグ用
    image: selenium/standalone-chrome-debug:latest
    ports:
      # - 4444:4444
      - 5900:5900
    networks:
      - cafe

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
      #socketファイルの共有
    volumes:
      - sockets:/app/tmp/sockets
      - public-data:/app/public
      - tmp-data:/app/tmp
    depends_on:
      - web
    networks:
      - cafe

networks:
  cafe:

volumes:
  pg-data:
  pgadmin-data:
  sockets:
  public-data:
  tmp-data:
  log-data:

